services:
  postgres:
    image: postgis/postgis
    container_name: subway_locations
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./utils/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "5433:5432"

volumes:
   pg_data: